Projekat-ISA-PSW/src/main/java/com/contoller/AppointmentsController.java, Projekat-ISA-PSW/src/main/java/com/dto/ClinicDTO.java, Projekat-ISA-PSW/src/main/java/com/model/Appointment.java, Projekat-ISA-PSW/src/main/resources/data.sql
Ovo su grafici poslovanja i rejtinzi doktora i klinike,treba jos jedan dio da se doda,pogledajte.
=> ratings of doctors and clinic graphs

Projekat-ISA-PSW/pom.xml, Projekat-ISA-PSW/src/main/java/com/ProjekatIsaPswApplication.java, Projekat-ISA-PSW/src/main/java/com/contoller/AppointmentsController.java, Projekat-ISA-PSW/src/main/java/com/contoller/RecipeController.java, Projekat-ISA-PSW/src/main/java/com/model/Appointment.java, Projekat-ISA-PSW/src/main/java/com/model/Recipe.java, Projekat-ISA-PSW/src/main/java/com/service/AppointmentService.java, Projekat-ISA-PSW/src/main/java/com/service/AppointmentServiceInterface.java, Projekat-ISA-PSW/src/main/java/com/service/RecipeService.java, Projekat-ISA-PSW/src/main/resources/data.sql
Dodat builder pattern na jedno mesto.
=> build pattern

Projekat-ISA-PSW/pom.xml, Projekat-ISA-PSW/src/main/java/com/ProjekatIsaPswApplication.java, Projekat-ISA-PSW/src/main/java/com/contoller/AppointmentsController.java, Projekat-ISA-PSW/src/main/java/com/contoller/RecipeController.java, Projekat-ISA-PSW/src/main/java/com/model/Appointment.java, Projekat-ISA-PSW/src/main/java/com/model/Recipe.java, Projekat-ISA-PSW/src/main/java/com/service/AppointmentService.java, Projekat-ISA-PSW/src/main/java/com/service/AppointmentServiceInterface.java, Projekat-ISA-PSW/src/main/java/com/service/RecipeService.java, Projekat-ISA-PSW/src/main/java/com/service/RecipeServiceInterface.java, Projekat-ISA-PSW/src/main/resources/data.sql
Dodata transakcija za overavanje recepta.
=> Feature 3.21 transaction

Projekat-ISA-PSW/src/main/java/com/contoller/AppointmentsController.java, Projekat-ISA-PSW/src/main/java/com/dto/AppointmentDTO.java, Projekat-ISA-PSW/src/main/java/com/model/Appointment.java, Projekat-ISA-PSW/src/main/java/com/model/Clinic.java, Projekat-ISA-PSW/src/main/java/com/model/Doctor.java, Projekat-ISA-PSW/src/main/java/com/model/RequestAppointment.java, Projekat-ISA-PSW/src/main/java/com/repository/AppointmentRepository.java, Projekat-ISA-PSW/src/main/java/com/repository/RequestAppointmentRepository.java, Projekat-ISA-PSW/src/main/java/com/service/AppointmentService.java, Projekat-ISA-PSW/src/main/java/com/service/EmailService.java, Projekat-ISA-PSW/src/main/java/com/service/RequestAppointmentService.java, Projekat-ISA-PSW/src/main/resources/data.sql
Dodavanje sobe pri odobravanju zahtjeva za pregled.
=> Feature 3.18. adding room to appointment

Projekat-ISA-PSW/src/main/java/com/contoller/AppointmentsController.java, Projekat-ISA-PSW/src/main/java/com/contoller/ClinicAdministratorController.java, Projekat-ISA-PSW/src/main/java/com/dto/AppointmentDTO.java, Projekat-ISA-PSW/src/main/java/com/dto/ClinicDTO.java, Projekat-ISA-PSW/src/main/java/com/dto/ReservationHospitalRoomDTO.java, Projekat-ISA-PSW/src/main/java/com/dto/ReservationHospitalRoomDTO2.java, Projekat-ISA-PSW/src/main/java/com/model/Clinic.java, Projekat-ISA-PSW/src/main/java/com/model/PatientRatedDoctor.java, Projekat-ISA-PSW/src/main/java/com/service/EmailService.java, Projekat-ISA-PSW/src/main/resources/data.sql
Slanje mejla o prihvatanju zahtjeva za pregled.
=> Bugfix 3.18 sending mail to patient

Projekat-ISA-PSW/src/main/java/com/contoller/AppointmentsController.java, Projekat-ISA-PSW/src/main/java/com/contoller/MedicalRecordController.java, Projekat-ISA-PSW/src/main/java/com/contoller/SurgeriesContoller.java
Dodavanje operacija u karton pacijenta.
=> surgery fix

Projekat-ISA-PSW/src/main/java/com/contoller/MedicalStaffController.java
Ispravila sam gresku. sada kod admina klinike prikazuje samo doktore koji pripadaju njegovoj klinici.
=> bugfix doctors list

Projekat-ISA-PSW/src/main/java/com/contoller/HospitalRoomController.java, Projekat-ISA-PSW/src/main/java/com/contoller/MedicalStaffController.java
Dodala sam ovdje da  klinicki admin moze pretrazivati samo sobe koje pripadaju njegovoj klinici.
=> Bugfix 3.16.3 hospital rooms list

Projekat-ISA-PSW/src/main/java/com/contoller/AppointmentsController.java, Projekat-ISA-PSW/src/main/java/com/contoller/HospitalRoomController.java, Projekat-ISA-PSW/src/main/java/com/contoller/MedicalStaffController.java
Ista greska je bila kao i kod ostalih funkcionalnosti,dodala sam ogranicenje da se vide samo zahtjevi od te odredjene klinike,imam jos na par mjesta da to dodam, to ce biti u iducim granama da znate.
=> Bugfix 3.4. appointment request view

Projekat-ISA-PSW/src/main/java/com/contoller/AppointmentsController.java, Projekat-ISA-PSW/src/main/java/com/model/Appointment.java, Projekat-ISA-PSW/src/main/java/com/repository/AppointmentRepository.java, Projekat-ISA-PSW/src/main/java/com/repository/DoctorRepository.java, Projekat-ISA-PSW/src/main/java/com/service/AppointmentService.java, Projekat-ISA-PSW/src/main/java/com/service/AppointmentServiceInterface.java, Projekat-ISA-PSW/src/main/resources/data.sql
Samo je odradjena transakcija za zakazianje unapred kreiranih pregleda.
=> transactions

Projekat-ISA-PSW/src/main/java/com/contoller/AppointmentsController.java, Projekat-ISA-PSW/src/main/java/com/contoller/PatientContoller.java, Projekat-ISA-PSW/src/main/java/com/model/RequestAppointment.java, Projekat-ISA-PSW/src/main/java/com/service/AppointmentService.java
Promenjene greske koje su bile na profilu pacijenta.
=> Bugfix 3.3 patient profile

Projekat-ISA-PSW/pom.xml, Projekat-ISA-PSW/src/main/java/com/contoller/ClinicController.java, Projekat-ISA-PSW/src/main/java/com/contoller/ClinicalCenterAdministratorContoller.java, Projekat-ISA-PSW/src/main/java/com/dto/AppointmentDTO.java, Projekat-ISA-PSW/src/main/java/com/dto/ClinicDTO.java, Projekat-ISA-PSW/src/test/java/com/ApplicationSuite.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/ProjekatIsaPswApplicationTests.java, Projekat-ISA-PSW/src/test/java/com/ProjekatIsaPswApplicationTests.java, Projekat-ISA-PSW/src/test/java/com/constants/ClinicCenterAdministratorConstants.java, Projekat-ISA-PSW/src/test/java/com/constants/ClinicConstants.java, Projekat-ISA-PSW/src/test/java/com/controller/ClinicControllerTest.java, Projekat-ISA-PSW/src/test/java/com/controller/ClinicalCenterAdministratorContollerTest.java, Projekat-ISA-PSW/src/test/resources/application-test.properties, Projekat-ISA-PSW/src/test/resources/test.sql
Stavila sam ovdje pocetne klase i pakete za testove . Koristila sam H2 bazu kao sto smo se dogovorili .
=> started creating packages for tests

Projekat-ISA-PSW/src/main/java/com/contoller/AppointmentsController.java, Projekat-ISA-PSW/src/main/java/com/dto/AppointmentDTO.java, Projekat-ISA-PSW/src/main/java/com/model/HospitalRoom.java, Projekat-ISA-PSW/src/main/java/com/service/AppointmentService.java, Projekat-ISA-PSW/src/main/java/com/service/AppointmentServiceInterface.java, Projekat-ISA-PSW/src/main/resources/data.sql, Projekat-ISA-PSW/src/test/java/com/IsaPsw/ProjekatIsaPswApplicationTests.java, Projekat-ISA-PSW/src/test/resources/application-test.properties, Projekat-ISA-PSW/src/test/resources/test.sql
Prva transakcija, 2 admina ne mogu u isto vrijeme rezervisati sobu.
=> Feature 3.18. transaction for reservation of hospital room

Projekat-ISA-PSW/src/main/java/com/dto/AppointmentDTO.java, Projekat-ISA-PSW/src/main/java/com/model/RequestAppointment.java, Projekat-ISA-PSW/src/main/java/com/service/AppointmentService.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/ApplicationSuite.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/constants/AppointmentConstants.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/constants/ClinicCenterAdministratorConstants.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/controller/ClinicalCenterAdministratorContollerTest.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/repository/AppointmentsRepositoryTest.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/service/AppointmentServiceTest.java, Projekat-ISA-PSW/src/test/resources/test.sql
Dodati testovi za AppointmentService.
=> TESTS-app service

Projekat-ISA-PSW/src/main/java/com/contoller/ClinicController.java, Projekat-ISA-PSW/src/main/java/com/service/AppointmentServiceInterface.java, Projekat-ISA-PSW/src/main/java/com/service/ClinicService.java, Projekat-ISA-PSW/src/main/java/com/service/ClinicServiceInterface.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/constants/ClinicConstants.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/controller/ClinicControllerTest.java, Projekat-ISA-PSW/src/test/resources/test.sql
Testovi za pretragu slobodnih klinika i doktora, vezano za zakazivanje pregleda(3.13).
=> getSearchClinicsAndDoctorsTets

Projekat-ISA-PSW/pom.xml, Projekat-ISA-PSW/src/main/java/com/contoller/PatientContoller.java, Projekat-ISA-PSW/src/main/java/com/model/Clinic.java, Projekat-ISA-PSW/src/main/java/com/model/Doctor.java, Projekat-ISA-PSW/src/main/java/com/service/AppointmentService.java, Projekat-ISA-PSW/src/main/java/com/service/ClinicService.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/constants/ClinicConstants.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/e2e/FirstPage.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/e2e/ScheduleAppointmentE2ETest.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/service/AppointmentServiceTest.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/service/ClinicServiceTest.java, Projekat-ISA-PSW/src/test/resources/test.sql
Uradjena dva testa za login. Jedan je pozitivan drugi je negativan.
=> Feature 7 e2e tests

Projekat-ISA-PSW/src/main/java/com/contoller/PatientContoller.java, Projekat-ISA-PSW/src/main/java/com/model/Clinic.java, Projekat-ISA-PSW/src/main/java/com/model/Doctor.java, Projekat-ISA-PSW/src/main/java/com/service/AppointmentService.java, Projekat-ISA-PSW/src/main/java/com/service/ClinicService.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/constants/ClinicConstants.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/service/AppointmentServiceTest.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/service/ClinicServiceTest.java, Projekat-ISA-PSW/src/test/resources/test.sql
Dodati testovi za ClinicService.
=> TESTS-clinics servis

Projekat-ISA-PSW/src/main/java/com/contoller/AppointmentsController.java, Projekat-ISA-PSW/src/main/java/com/contoller/ClinicController.java, Projekat-ISA-PSW/src/main/java/com/dto/AppointmentDTO.java, Projekat-ISA-PSW/src/main/java/com/model/Appointment.java, Projekat-ISA-PSW/src/main/java/com/model/Doctor.java, Projekat-ISA-PSW/src/main/java/com/model/RequestAppointment.java, Projekat-ISA-PSW/src/main/java/com/service/AppointmentService.java, Projekat-ISA-PSW/src/main/java/com/service/AppointmentServiceInterface.java, Projekat-ISA-PSW/src/main/java/com/service/RequestAppointmentService.java, Projekat-ISA-PSW/src/main/resources/data.sql, Projekat-ISA-PSW/src/test/java/com/IsaPsw/ApplicationSuite.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/controller/AppointmentsControllerTest.java, Projekat-ISA-PSW/src/test/resources/test.sql
Dodala sam cijenu za  preglede.
=> Bugfix 3.4.2 fast appointments price

Projekat-ISA-PSW/src/main/java/com/contoller/ClinicController.java, Projekat-ISA-PSW/src/main/java/com/model/Clinic.java, Projekat-ISA-PSW/src/main/java/com/service/ClinicService.java, Projekat-ISA-PSW/src/main/java/com/service/ClinicServiceInterface.java, Projekat-ISA-PSW/src/main/resources/data.sql, Projekat-ISA-PSW/src/test/resources/test.sql
Transakcija vezana za mijenjanje podataka klinike.
=> Added transaction for changing clinic data

Projekat-ISA-PSW/pom.xml, Projekat-ISA-PSW/src/main/java/com/model/Appointment.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/service/AppointmentServiceUnitTest.java
=> TESTS unit tests

Projekat-ISA-PSW/src/main/java/com/contoller/ClinicController.java, Projekat-ISA-PSW/src/main/resources/data.sql, Projekat-ISA-PSW/src/test/java/com/IsaPsw/ApplicationSuite.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/controller/AppointmentsControllerTest.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/e2e/ScheduleAppointmentE2ETest.java, Projekat-ISA-PSW/src/test/resources/test.sql
Dodato je da se adresa bira preko mape.
=> Bugfix new clinic address

Projekat-ISA-PSW/src/main/java/com/contoller/AppointmentTypeController.java, Projekat-ISA-PSW/src/main/java/com/contoller/ClinicController.java, Projekat-ISA-PSW/src/main/java/com/dto/AppointmentTypeDTO.java, Projekat-ISA-PSW/src/main/resources/data.sql, Projekat-ISA-PSW/src/test/java/com/IsaPsw/ApplicationSuite.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/controller/AppointmentsControllerTest.java, Projekat-ISA-PSW/src/test/java/com/IsaPsw/e2e/ScheduleAppointmentE2ETest.java, Projekat-ISA-PSW/src/test/resources/test.sql
Popravila sam neke funkcionalnosti vezane za tip pregleda.
=> Bugfix 3.4. adding type

Projekat-ISA-PSW/src/main/java/com/contoller/AppointmentsController.java, Projekat-ISA-PSW/src/main/java/com/contoller/MedicalStaffController.java, Projekat-ISA-PSW/src/main/java/com/service/ClinicService.java, Projekat-ISA-PSW/src/main/java/com/service/EmailService.java
=> fixed some bugs
